version: "3"

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8085:8085"
    volumes:
      - ./backend:/app
    environment:
      - NODE_ENV=production

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
